config/routes.rb
NorewarRails::Application.routes.draw do

  root 'welcome#index'
  get 'error' => 'welcome#error'

  resources :users do
    collection do
      get 'logout'
      post 'login'
    end
  end

  resources :codes do
    member do
      get 'default'
    end
    
    collection do
      get 'upload'
      post 'file'
    end
  end

  resources :matches do
    member do
      post 'view'
    end
  end

  resources :contests do
    member do
      get 'join'
      get 'open'
      get 'test'
      get 'recover'
    end
  end
end

app/views/template/navbar.html.erb
<div class='nav-bar'>
	<div class='container'>
		<%= link_to 'Root', root_path, id: 'root_link', class: 'nav-btn pull-left' %>
		<%= link_to 'Codes', codes_path, class: 'nav-btn pull-left' %>
		<%= link_to 'Match', matches_path, class: 'nav-btn pull-left' %>
		<%= link_to 'Contests', contests_path, class: 'nav-btn pull-left' %>
		<a class='nav-btn pull-left' href='##'>Discussion</a>
		<a class='nav-btn pull-right <%= 'hide' unless @user.nil? %>'
			id='login_lst' href='##'>Login<small>▼</small></a>
		<span class='pull-right <%= 'hide' if @user.nil? %>' id='welcome_span'>
			<span id='welcome_txt' class='nav-text'>Welcome,
			<%= @user.name unless @user.nil? %>!</span>
			<%= link_to 'Logout', logout_users_path, class: 'btn' %>
		</span>
	</div>
	<% if @user.nil? %>
	<div class='login'>
		<div class='container'>
			<form class='hide pull-right' id='login_form'>
				Enter your credentials:
				<input type='text' id='username_txt' class='text-long' placeholder='User'/>
				<input type='password' id='password_txt' class='text-long' Placeholder='Password'/>
				<div id='recaptcha_widget'>
					<!-- <div id='recaptcha_image'></div> -->
					<!-- <input class='text-long' type='text' id='recaptcha_response_field' Placeholder='Enter the words above'/> -->
				</div>
				<!-- <%= recaptcha_tags display: {:theme => 'red'}, ajax: true %> -->
				<div class='btn-line'>
					<a id='reg_btn' class='pull-right btn' href='##'>Sign up</a>
					<a id='log_btn' class='pull-right btn' href='##'>Sign in</a>
				</div>
			</form>
		</div>
	</div>
	<% end %>

	<div class='nav-background'></div>
</div>

app/views/template/viewer.html.erb
<div class='viewer'>
	<input type='hidden' id='match_id' value="<%= @match._id %>" />
	<table class='pull-left'>
		<tbody>
			<% 16.times do |i| %>
				<tr>
					<% 16.times do |j| %>
						<td id='map_<%= i %>_<%= j %>' class='team0' team='0'>
							<span id="direction_<%= i %>_<%= j %>" class='hide viewer-direction'></span>
						</td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>
	<div class='viewer-bar pull-left'>
		<% @codes.each_with_index do |code, i| %>
			<h3 class='team<%= i %>'>
				<span><%= code[:user] %></span>
				/
				<span><%= code[:name] %></span>
				*
				<span id='cnt_<%= i+1 %>'>0</span>
			</h3>
		<% end %>
		<div class='btn-line'>
			<a href='##' id='play_btn' class='btn btn-small'>Play</a>
			<a href='##' id='pause_btn' class='btn btn-small'>Pause</a>
		</div>
		<div class='btn-line'>
			<a href='##' id='slow_btn' class='btn btn-small'>Slower</a>
			<a href='##' id='fast_btn' class='btn btn-small'>Faster</a>
		</div>
		<div class='btn-line'>
			<input id='direction_chk' type='checkbox'/><span>Direction</span>
		</div>
		FPS:
		<span id='speed_span'>20</span>
	</div>
</div>