config/routes.rb
NorewarRails::Application.routes.draw do

  root 'welcome#index'
  get 'error' => 'welcome#error'

  resources :users do
    collection do
      get 'logout'
      post 'login'
    end
  end

  resources :codes do
    member do
      get 'default'
    end
    
    collection do
      get 'upload'
      post 'file'
    end
  end

  resources :matches do
    member do
      post 'view'
    end
  end

  resources :contests do
    member do
      get 'join'
      get 'open'
      get 'test'
      get 'recover'
    end
  end
end

app/models/contest.rb
class Competitor
	include MongoMapper::EmbeddedDocument

	key :score, Integer
	key :user_id, ObjectId

	attr_accessible :score, :user_id

	def user
		User.find user_id
	end
end

class Contest
	include MongoMapper::Document

	key :name, String
	key :description, String
	many :competitors
	key :status, Integer
	key :round, Integer
	key :job_ids, Array
	many :jobs, in: :job_ids
	key :owner_id, ObjectId
	timestamps!

	STATUS_MSG = [
		'Open',
		'Going on',
		'Judging',
		'Ended'
	]

	def status_msg
		STATUS_MSG[status]
	end

	def rank
		competitors.sort do |i, j|
			j.score <=> i.score
		end
	end

	def next_round
		self.round = self.round - 1
		competitors = rank
		count = competitors.size / 2
		count.times do |i|
			random = SecureRandom.hex 8
			com1 = competitors[2 * i].user
			com2 = competitors[2 * i + 1].user
			if com1.default.nil? || com2.default.nil?
				if com1.default.nil?
					competitors[2 * i].score -= 10
				else
					competitors[2 * i].score += 1
				end
				if com2.default.nil?
					competitors[2 * i + 1].score -= 10
				else
					competitors[2 * i + 1].score += 1
				end
			else
				self.status = 2
				match_name = "#{name}-#{round}-#{com1.name}-vs-#{com2.name}-#{random}"
				match = Match.create name: match_name, status: 0
				match.users.push com1
				match.codes.push com1.default
				match.users.push com2
				match.codes.push com2.default
				match.save
				jid = JudgeWorker.perform_in(1.seconds, match._id, _id)
				job = Job.create jid: jid, users: [com1._id, com2._id]
				jobs.push job
			end
		end
		if self.status != 2
			self.status = if self.round > 0 then 1 else 3 end
		end
		save
	end

	def joint?(user)
		competitors.each do |competitor|
			return true if user._id == competitor.user_id
		end
		false
	end

	def owner
		User.find owner_id
	end

	def admin?(user)
		user._id == owner_id
	end

	attr_accessible :name, :scores, :status, :competitors, :round, :owner_id, :description, :jobs
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
	before_action :current_user!

	def index
	end

	def new
		@contest = Contest.new
	end

	def create
		require_params params, false, :contest
		require_params params[:contest], false, :name, :round

		@contest = Contest.create name: params[:contest][:name],
			round: params[:contest][:round].to_i, status: 0, owner_id: @user._id,
			description: params[:contest][:description]

		redirect_to @contest
	end

	def join
		require_contest false, 0

		@contest.competitors.push Competitor.new(score: 0, user_id: @user._id)
		@contest.save
		redirect_to @contest
	end

	def show
		require_contest
	end

	def open
		require_contest true, 0

		raise ClientException.new 'Competitor size must be even!' unless @contest.competitors.size % 2 == 0
		@contest.status = 1
		@contest.save
		redirect_to @contest
	end

	def test
		require_contest true, 1

		@contest.next_round
		redirect_to @contest
	end

	def destroy
		require_contest
		@contest.destroy
		redirect_to contests_path
	end

	def recover
		require_contest true
		@contest.status = 1
		@contest.jobs.destroy_all
		@contest.save
		redirect_to @contest
	end

	private

	def require_contest(admin = false, status = nil)
		require_params params, false, :id
		@contest = Contest.find params[:id]
		raise ClientException.new 'Contest not found!'if @contest.nil?
		raise ClientException.new 'You have no permission!' if admin && !@contest.admin?(@user)
		unless status.nil? || status == @contest.status
			raise ClientException.new "Contest status required: #{Contest::STATUS_MSG[status]}"
		end
	end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/index.html.erb
<h1>
	<span><%= link_to '$', root_path %></span>
	/
	<span><%= link_to 'Contests', contests_path %></span>
	<%= link_to 'New', new_contest_path, class: 'btn pull-right' %>
</h1>
<table class='table table-full'>
	<tr>
		<th>Name</th>
		<th>Status</th>
		<th>Rounds Left</th>
		<th>Competitors</th>
		<th>Created At</th>
		<th>Updated At</th>
	</tr>
	<% Contest.each do |contest| %>
	<tr>
		<td><%= link_to contest.name, contest %></td>
		<td><%= contest.status_msg %></td>
		<td><%= contest.round %></td>
		<td><%= contest.competitors.count %></td>
		<td><%= contest.created_at %></td>
		<td><%= contest.updated_at %></td>
	</tr>
	<% end %>		
</table>

app/views/contests/new.html.erb
<%= form_for @contest do |f| %>
	<h1>
		<span>$</span>
		/
		<span>Contest</span>
		/
		<%= f.text_field :name, class: 'text-long text-large text-title inline', placeholder: 'Enter Name...', required: true %>
	</h1>
	<%= f.label :description, for: :description %>
	<br/><%= f.text_area :description %><br/>
	<%= f.label :round, for: :round %>
	<%= f.text_field :round, class: 'text-long', placeholder: 'Enter Rounds...', required: true %>
	<%= f.submit 'Save', class: 'btn' %>
<% end %>

app/views/contests/show.html.erb
<h1>
	<span><%= link_to '$', root_path %></span>
	/
	<span><%= link_to 'Contests', contests_path %></span>
	/
	<span><%= link_to @contest.name, @contest %></span>

	<%= link_to 'Join', join_contest_path, class: 'btn pull-right' if !@contest.joint?(@user) && @contest.status == 0 %>

	<% if @contest.admin? @user %>
		<%= link_to 'Open', open_contest_path, class: 'btn pull-right' if @contest.status == 0 %>
		<%= link_to 'Test', test_contest_path, class: 'btn pull-right' if @contest.status == 1 %>
		<%= link_to 'Delete', @contest, method: :delete, class: 'btn btn-alert pull-right' %>
	<% end %>
</h1>
<div class='contest container'>
	<table class='table contest-table pull-left'>
		<tr>
			<th>Rank</th>
			<th>Competitor</th>
			<th>Score</th>
		</tr>
		<% @contest.rank.each_with_index do |competitor, i| %>
		<tr>
			<td><%= i %></td>
			<td><%= competitor.user.name %></td>
			<td><%= competitor.score %></td>
		</tr>
		<% end %>
	</table>
	<div class='contest-detail'>
		<h2>Description</h2>
		<% unless @contest.description.nil? || @contest.description.empty? %>
			<% @contest.description.each_line do |line| %>
				<p><%= line %></p>
			<% end%>
		<% else %>
			<p>None</p>
		<% end %>

		<h3>
		<% if @contest.status == 0 %>
			Open For Competitors
		<% elsif @contest.status == 1 %>
			Waiting For Round: <%= @contest.round - 1 %>
		<% elsif @contest.status == 2 %>
			Judging Round: <%= @contest.round %>
		<% else %>
			Ended
		<% end %>
		</h3>
		<h3>Owner: <%= @contest.owner.name %></h3>
	</div>
</div>