config/routes.rb
NorewarRails::Application.routes.draw do

  root 'welcome#index'
  get 'error' => 'welcome#error'

  resources :users do
    collection do
      get 'logout'
      post 'login'
    end
  end

  resources :codes do
    member do
      get 'default'
    end
    
    collection do
      get 'upload'
      post 'file'
    end
  end

  resources :matches do
    member do
      post 'view'
    end
  end

  resources :contests do
    member do
      get 'join'
      get 'open'
      get 'test'
      get 'recover'
    end
  end
end

app/models/code.rb
class Code
	include MongoMapper::Document

	key :name, String
	key :code, String
	belongs_to :user

	timestamps!

	attr_accessible :name, :code
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
	before_action :current_user!

	def new
		@code = Code.new
		@code.code = ''
	end

	def create
		require_params params, false, :code
		require_params params[:code], false, :name
		require_params params[:code], true, :code
		code = @user.codes.create name: params[:code][:name], code: params[:code][:code]
		redirect_to code
	end

	def show
		require_code
	end

	def index
		@codes = @user.codes
	end

	def destroy
		require_code
		@code.destroy

		redirect_to codes_path
	end

	def edit
		require_code
	end

	def update
		require_params params, false, :code
		require_params params[:code], false, :name
		require_params params[:code], true, :code
		require_code

		@code.name = params[:code][:name]
		@code.code = params[:code][:code]
		@code.save
		redirect_to @code
	end

	def upload
		@code = Code.new
		@code.code = ''
	end

	def file
		require_params params, false, :code
		require_params params[:code], false, :name
		require_params params[:code], true, :file

		file = params[:code][:file].read
		code = @user.codes.create name: params[:code][:name], code: file
		redirect_to code
	end

	def default
		require_code

		@user.set default_id: params[:id]
		@code.save
		redirect_to @code
	end

	private

	def require_code
		require_params params, false, :id
		@code = @user.codes.find params[:id]
		raise ClientException.new "Code not found!" if @code.nil?
	end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_editor.html.erb
<%= form_for @code, html: { class: 'editor' } do |f| %>
	<h1>
		<span><%= link_to @user.name, codes_path %></span>
		/
		<%= f.text_field :name, class: 'text-long text-large text-title inline', placeholder: 'Enter Name...', required: true %>
	</h1>
	<div class='editor-container'>
		<div class='editor-bar'>
			<div class='editor-info pull-left'>
				<span id='line_info'></span>
			</div>
			<%= f.submit 'Save', class: 'btn pull-right' %>
		</div>
		<div class="code-line-num-container">
			<div class="code-line-num" id="code-line-num"></div>
		</div>
		<div class="editor-area-container">
			<%= f.text_area :code, class: 'editor-area' %>
		</div>
	</div>
<% end %>

app/views/codes/edit.html.erb
<%= render 'editor' %>

app/views/codes/index.html.erb
<h1>
	<span><%= link_to @user.name, codes_path %></span>
	/
	<%= link_to 'Upload', upload_codes_path, class: 'btn pull-right' %>
	<%= link_to 'Create', new_code_path, class: 'btn pull-right' %>
</h1>
<table class='table table-full'>
	<tr>
		<th>Name</th>
		<th>Lines</th>
		<th>Created At</th>
		<th>Updated At</th>
	</tr>
	<% @codes.each do |code| %>
		<tr>
			<td><%= link_to code.name + if code._id == @user.default_id then '(Default)' else '' end, code %></td>
			<td><%= code.code.lines.size %></td>
			<td><%= code.created_at %></td>
			<td><%= code.updated_at %></td>
		</tr>
	<% end %>
</table>

app/views/codes/new.html.erb
<%= render 'editor' %>

app/views/codes/show.html.erb
<h1>
	<span><%= link_to @user.name, codes_path %></span>
	/
	<span><%= link_to @code.name + if @code._id == @user.default_id then '(Default)' else '' end, @code %></span>
</h1>
<div class='code'>
	<div class='code-bar'>
		<div class='code-info pull-left'>
			<span><%= @code.code.lines.size %></span>
			<span>line(s)</span>
		</div>
		<%= link_to 'Delete', @code, method: 'delete', class: 'btn btn-alert pull-right' %>
		<%= link_to 'Edit', edit_code_path(@code), class: 'btn pull-right' %>
		<%= link_to 'Set Default', default_code_path(@code), class: 'btn pull-right' %>
	</div>
	<table>
		<% i = 1 %>
		<% @code.code.each_line do |line| %>
			<tr>
				<td class='code-line-num'><%= i %></td>
				<% i = i + 1 %>
				<td class='code-line'>
					<pre><%= line %></pre>
				</td>
			</tr>
		<% end %>
		<tr class='code-line-cover'>
			<td class='code-line-num'></td>
			<td></td>
		</tr>
	</table>
</div>

app/views/codes/upload.html.erb
<%= form_for @code, url: { action: 'file' }, html: { class: 'editor' } do |f| %>
	<h1>
		<span><%= link_to @user.name, codes_path %></span>
		/
		<%= f.text_field :name, class: 'text-long text-large text-title inline', placeholder: 'Enter Name...', required: true %>
	</h1>
	<%= f.file_field :file, required: true %>
	<%= f.submit class: 'btn' %>
<% end %>